### ISSUE TITLE
lack of `arma::` prefix causes compiler confusion

### ISSUE THREAD

**Issue by conradsnicta** [nielsrhansen/sglOptim#2]
https://github.com/nielsrhansen/sglOptim/blob/484d452f3e1c93361310a81f1668aa10b943feb2/inst/include/sgl/objective/sgl_gl_loss_base.h#L407

In the above line, calls to armadillo functions lack the `arma::` prefix, causing compiler confusion when using Armadillo 9.400+.

Proposed fix is in submitted PR: https://github.com/nielsrhansen/sglOptim/pull/1

CC: @eddelbuettel

**Comment by eddelbuettel** [comment]
Thanks Conrad -- I think I CCed you on the email I send about this earlier today (circa 14 hours ago).

**Comment by TianshuFeng** [comment]
Same problem here. This problem prevents me from installing the package directly from GitHub with errors.

**Comment by eddelbuettel** [comment]
So edit as suggested -- you need the `arma::` namespace qualifier.

**Comment by TianshuFeng** [comment]
Thanks for the suggestion! I solved it by installing an older version of RcppArmadillo.

**Comment by nielsrhansen** [comment]
Issue fixed by accepting pull request.

**Comment by eddelbuettel** [comment]
Let me if I can help getting the two packages back onto CRAN.

**Comment by nielsrhansen** [comment]
Thanks. They were removed due to "Stripping debug symbols". I have dropped this, and the packages have been resubmitted to CRAN. There is an additional issue with rchk, that I don't believe is simple to fix (some design decisions related to the use of PROTECT). For now, I was informed that the packages could remain on CRAN.

**Comment by eddelbuettel** [comment]
Sounds good!  The `rchk` issues are tricky with C++ code.  It isn't always right and they know it...
